"""add email archive table

Revision ID: add_email_archive_table
Revises: add_system_settings_table
Create Date: 2025-08-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_email_archive_table'
down_revision = 'add_system_settings_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_type', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('cc_emails', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bcc_emails', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('smtp_server', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_archive_id'), 'email_archive', ['id'], unique=False)
    op.create_index(op.f('ix_email_archive_email_type'), 'email_archive', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_archive_recipient_email'), 'email_archive', ['recipient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_archive_recipient_email'), table_name='email_archive')
    op.drop_index(op.f('ix_email_archive_email_type'), table_name='email_archive')
    op.drop_index(op.f('ix_email_archive_id'), table_name='email_archive')
    op.drop_table('email_archive')
    # ### end Alembic commands ###
